### ISSUE TITLE
Inconsistent use of letter case

### ISSUE THREAD

**Issue by nikita-volkov** [RyanGlScott/text-show#13]
The coexistence of names like `showt` and `printT` is really bothering and confusing. It is an absence of a convention across a single library. It would be so much better if you just picked either one and followed thru with the rest of the library. 

I mean it should be either `showt` and `printt` or `showT` and `printT`. A chaotic mixture of counterconventions is a usability killer.

**Comment by nikita-volkov** [comment]
BTW, the name `showt` follows none of the existing Haskell conventions. If you were following the truely awkward as per my taste, but at least standard naming convention of `fmap`, `mappend`, that would make the function name `tshow`. 

Overall there's clearly a lot of issues with the naming in this library. My suggestion is to provide full names (`showText`, `showLazyText`) and leave it to e.g., wrapper libraries, to come up with shorthands and other usability optimizations. That way you'll at least take off the naming optimization problem from yourself altogether.

**Comment by RyanGlScott** [comment]
Hey there. I apologize that the naming conventions are haphazard—trying to come up with satisfying names is the most challenging part of this library.

I'm open to changing some names, but I would like to point out that there is _some_ precedence for the `showb`/`showt`/`showtl` naming convention that I've adopted. Namely, I took it directly from [`Text.Show`](http://hackage.haskell.org/package/base-4.8.1.0/docs/Text-Show.html) in `base`, where certain `show`-related functions that return `ShowS` have an `s` to mark them as such (e.g., `shows`, `showsPrec`).

Admittedly, `Text.Show` isn't entirely self-consistent, since there also exist `showChar` and `showString`, which return `ShowS` but don't follow the `-s` suffix convention. But the spirit of the idea seems noble, and `text-show`'s spiritual predecessor [`bytestring-show`](http://hackage.haskell.org/package/bytestring-show) also uses a similar [`-p` suffix convention](http://hackage.haskell.org/package/bytestring-show-0.3.5.6/docs/Text-Show-ByteString.html#t:Show), so I decided to adopt that naming philosophy.

Unfortunately, as you've pointed out, this becomes less satisfying linguistically when you try to tack on suffixes to functions that already end with several consonants. For example, `print` becomes `printtl`, which doesn't English well. My attempt to mitigate this was to capitalize the suffixes as necessary to aid in pronunciation. Now we've got a garbled mess of naming conventions.

So what can we do? Some options include:

1. Spelling everything out, e.g., `showb` becomes `showBuilder`, `printtl` becomes `printTextLazy`, etc. Personally, I'm disinclined towards this option since it adds a lot more keystrokes for common tasks, e.g., this:

    ```haskell
    data Example = Example Int Int
    instance TextShow Example where
        showb (Example i1 i2) = showb i1 <> showbSpace <> showb i2
    ```

    becomes this:

    ```haskell
    data Example = Example Int Int
    instance TextShow Example where
        showBuilder (Example i1 i2) = showBuilder i1 <> showBuilderSpace <> showBuilder i2
    ```

2. Turn the suffixes into prefixes, e.g., `printtl` becomes `tlprint`. IMO, this doesn't really change much—it just bikesheds about the placement of the keywords. For every function like `fmap` and `mappend`, there's also functions like `liftA` and `mapM`, so Haskell itself doesn't seem to have made up its mind about which is better :)
3. Uniformly make all suffixes lowercase. This makes things more consistent without breaking the API too much, but there's also the issue of consonant collision in functions like `printtl`.
4. Uniformly make all suffixes uppercase. This makes it easier to predict what to type, and doesn't deviate too much from the convention in `Text.Show` in `base`. It would break the API significantly in that many users would have to redefine their `TextShow` instances (since `showb` becomes `showB`) if they're not using Template Haskell or GHC generics.

Personally, if I had to change something, I'd most inclined toward option 4. Then again, you're pretty much _the_ user of `text-show` at this point (that I'm aware of), so if you feel that 4 would be unacceptable, please speak up.

**Comment by nikita-volkov** [comment]
> you're pretty much the user

There's almost 2k Hackage downloads, so I'm hardly the only user :)

> Spelling everything out, e.g., showb becomes showBuilder, printtl becomes printTextLazy, etc.

I recommend that option, since it's neutral concerning the naming conventions, and relieves you as the maintainer from the problem of naming conventions altogether. Anyone who wants shorter versions can release a package with aliases or declare them in his project internally.

This package has enough of other concerns besides naming conventions. 

> Uniformly make all suffixes uppercase.

If you're still determined to go with shortcuts, that one is the most viable option IMO.

**Comment by RyanGlScott** [comment]
I suspect a lot of those downloads are due to Travis-CI, but now that I check, http://packdeps.haskellers.com/reverse/text-show does show that other people are using it! I should probably break stuff sooner than later, in that case :)

> If you're still determined to go with shortcuts, that one is the most viable option IMO.

Then I'll probably do just that. I want to try and complete some other big changes before a `text-show-3.0` release, so this will probably need to wait a bit.

**Comment by nikita-volkov** [comment]
While we're at it, I believe, the word order is also an issue. "LazyText" makes more sense then "TextLazy", and hence the "LT" abbreviated form instead of "TL" and so on. I'm hardly alone in that, e.g. ["string-conversions"](http://hackage.haskell.org/package/string-conversions-0.4/docs/Data-String-Conversions.html), ["basic-prelude"](http://hackage.haskell.org/package/basic-prelude-0.5.0/docs/CorePrelude.html#t:LText). Also, according to Hayoo, the order I suggest is definitely a winner:
[results of "LazyText"](http://hayoo.fh-wedel.de/?query=LazyText) vs [results of "TextLazy"](http://hayoo.fh-wedel.de/?query=TextLazy).

I suspect you were strayed off by the namespaces in the "text" library, but this really doesn't have anything to do with the name of the thing. That is, besides the namespacing being quite questionable there.

**Comment by RyanGlScott** [comment]
At this point, I don't think I'm going to be overhauling the naming conventions again.
