### ISSUE TITLE
Use DefaultSignatures to provide default showbPrec via genericShowbPrec

### ISSUE THREAD

**Issue by xich** [RyanGlScott/text-show#14]
Can you use DefaultSignatures to make defining instances even simpler? Ideally:

```
data Foo = Foo deriving (Generic)
instance TextShow Foo
```

As an example, `Hashable` does this:

https://hackage.haskell.org/package/hashable-1.2.3.3/docs/src/Data-Hashable-Class.html#Hashable

You can just write:

```
data Foo = Foo deriving (Generic)
instance Hashable Foo
```

and all the right things happen.

**Comment by RyanGlScott** [comment]
I think there are two reasons why I never turned on `-XDefaultSignatures`:

1. Up until GHC 8.0, the `TextShow.Generic` couldn't do everything that `TextShow.TH` could since GHC generics didn't work on unlifted data types. This soon won't be an issue.
2. `TextShow`'s methods are defined in terms of each other, so there's a tricky design question w.r.t. which methods get default signatures. Should we do this?

    ```haskell
    class TextShow a where
      showb :: a -> Builder
      default :: (Generic a, GTextShow (Rep a)) => a -> Builder
      showb = genericShowb
      
      showbPrec :: Int -> a -> Builder
      default showbPrec :: (Generic a, GTextShow (Rep a)) => Int -> a -> Builder
      showbPrec = genericShowbPrec
      
      showbList :: [a] -> Builder
      default showbList :: (Generic a, GTextShow (Rep a)) => [a] -> Builder
      showbList = genericShowbList
    ```

If this is how `TextShow` is defined, then a user could manually implement `showbPrec` but not `showb`, and as a result, `showb` would still use the default implementation. This would mean that `showbPrec 0 =/= showb`!

If there were some way to switch off the default behavior whenever at least method was manually implemented (?), I'd be much less hesitant.

**Comment by xich** [comment]
1. Pre-8.0, I would have thought the `deriving (Generic)` would fail if the type contained unlifted types... so wouldn't the default implementation just notice a missing Generic constraint and complain, forcing the user to use TextShow.TH? I guess what I'm saying is, wouldn't adding the default just cause a type error when trying to use the default on something containing unlifted types? Surely that is a rare case?

2. Could you not just:

```
class TextShow a where
    showbPrec :: Int -> a -> Builder
    default showbPrec :: (Generic a, GTextShow (Rep a)) => Int -> a -> Builder
    showbPrec = genericShowbPrec

    showb :: a -> Builder
    showb = showbPrec 0

    showbList :: [a] -> Builder
    showbList = showbListWith showb
```

**Comment by xich** [comment]
Oh, I guess what I proposed in 2 would still suffer from that problem. It would be nice if it only fell back on the generic instance if none well defined... wonder how to do that.

**Comment by RyanGlScott** [comment]
Any thoughts on this, @xich?

**Comment by xich** [comment]
Sorry, I've lost the thread a bit here. Can you write out the hypothetical class definition you are proposing.

Anecdotally, our use-cases look equally split between `showb` and `showbPrec`. The former is used for hand-written instances, and the latter is always just `showbPrec = genericShowbPrec`.

**Comment by RyanGlScott** [comment]
Currently, the definition of `TextShow` is as follows:

```haskell
class TextShow a where
    {-# MINIMAL showbPrec | showb #-}

    showbPrec :: Int -> a -> Builder
    showbPrec _ = showb

    showb :: a -> Builder
    showb = showbPrec 0

    -- Other methods defined in terms of these
```

What I'm wondering is if instead, we should do this:

```haskell
class TextShow a where
    {-# MINIMAL showbPrec #-}

    showbPrec :: Int -> a -> Builder
    default showbPrec :: (Generic a, GTextShow (Rep a)) => Int -> a -> Builder
    showbPrec = genericShowbPrec

    showb :: a -> Builder
    showb = showbPrec 0

    -- Other methods defined in terms of these
```

-----

The pros of the current approach are:

* It matches what the original `Show` class does.
* It allows users to define `TextShow` methods either through `showbPrec` or `showb`—whichever they prefer.

The cons of the current approach are:

* It requires users to manually provide generic defaults which, judging by this ticket, is a fairly common use case.

-----

The pros of the proposed new approach are:

* It supports generic defaults right out of the box.

The cons of the proposed new approach are:

* It would subtly break any existing `TextShow` instances that only define `showb`, because under this new class definition, an instance without an explicitly defined `showbPrec` would get a generic default, likely causing `showb 0 /= showbPrec`.
* It would deviate from the original `Show` class. (Perhaps this isn't so important, as `TextShow` deviates in other ways as well.)

-----

I'm inclined to adopt the proposed new approach if there's interest, but with an emphasis on the interest part—we'd have to change the semantics of `TextShow` to make this work, so there's inevitably going to be some heartburn in switching over all existing instances that only define `showb`.

**Comment by RyanGlScott** [comment]
On second thought, I think I won't do this. This is rather enormous breaking change with just as many cons as pros.

I think a more viable approach is to create a newtype with a `Generic`-based `TextShow` instance, and encourage folks who want that as the default to use it in conjunction with `DerivingVia`. I've opened https://github.com/RyanGlScott/text-show/issues/37 to track this.
