### ISSUE TITLE
text-show-0.6 can't find overlap.h

### ISSUE THREAD

**Issue by peti** [RyanGlScott/text-show#2]
The latest version refers to a system header `overlap.h`. Which package provides that file? I have no clue where to find that?

http://hydra.cryp.to/build/526196/nixlog/2/raw shows the build log on our CI.

**Comment by RyanGlScott** [comment]
Whoops! `overlap.h` is a CPP hack that I use to work around `OverlappingInstances` being deprecated on GHC 7.10. I forgot to put this in the `extra-source-files` section of `text-show.cabal`, which is why it wasn't downloaded from Hackage. I'll update the Hackage version with this change. Please reopen this bug if you continue to experience problems.
