### ISSUE TITLE
Feature request: faster encoding for enumeration types

### ISSUE THREAD

**Issue by andrewthad** [RyanGlScott/text-show#21]
In [this benchmark](https://github.com/RyanGlScott/text-show/pull/20), the results come out like this on my computer:

    benchmarking Enumeration Type (strict Text)/String Show, then Text.pack
    time                 108.6 ns   (107.9 ns .. 109.7 ns)
                         0.999 R²   (0.999 R² .. 1.000 R²)
    mean                 108.3 ns   (107.9 ns .. 109.3 ns)
    std dev              2.054 ns   (1.077 ns .. 4.093 ns)
    variance introduced by outliers: 25% (moderately inflated)
                 
    benchmarking Enumeration Type (strict Text)/Text Show (TH)
    time                 85.60 ns   (85.47 ns .. 85.74 ns)
                         1.000 R²   (1.000 R² .. 1.000 R²)
    mean                 85.59 ns   (85.48 ns .. 85.88 ns)
    std dev              521.2 ps   (254.7 ps .. 1.059 ns)
             
    benchmarking Enumeration Type (strict Text)/Manually written text show
    time                 8.574 ns   (8.564 ns .. 8.585 ns)
                         1.000 R²   (1.000 R² .. 1.000 R²)
    mean                 8.571 ns   (8.563 ns .. 8.584 ns)
    std dev              32.87 ps   (23.15 ps .. 44.46 ps)

The manually written one by far the fastest, presumably because GHC can just lift all the results out of the case statement. I don't actually need this, but I thought it would be worth bringing up that `text-show`'s template haskell might be able to optimize its generated code in cases like this.

**Comment by RyanGlScott** [comment]
Interesting! I'm still not sure if we can immediately draw any conclusions from this, however, because the benchmarks you added in #20 don't quite do an apples-to-apples comparison.

In particular, your `manualColorRendering` function is doing less work than what a TH-derived `TextShow` instance has to do. `manualColorRendering` encodes strings directly to strict `Text`, whereas in the TH-derived `TextShow` instance for `Color`:

```haskell
    deriveTextShow ''Color
  ======>
    instance text-show-3.2.2:TextShow.Classes.TextShow Color where
      text-show-3.2.2:TextShow.Classes.showbPrec
        = \ p_a7vf value_a7vg
            -> text-show-3.2.2:TextShow.TH.Internal.showbPrecConst
                 (case value_a7vg of {
                    Red -> Data.Text.Internal.Builder.fromString "Red"
                    Green -> Data.Text.Internal.Builder.fromString "Green"
                    Blue -> Data.Text.Internal.Builder.fromString "Blue"
                    Orange -> Data.Text.Internal.Builder.fromString "Orange"
                    Violet -> Data.Text.Internal.Builder.fromString "Violet" })
                 p_a7vf
                 value_a7vg
```

implements `showbPrec`, and `showt` uses the default implementation of `toStrict . toLazyText . showbPrec 0`.

I do think your hunch is correct in that going through a `Builder` incurs a performance penalty for small datatypes like `Color`, but I'd like to how much of a penalty before I take action. Can you benchmark the following as well:

* The above `TextShow Color` instance, but instead of implementing `showbPrec`, implement `showtPrec`. (You can get rid of the `showbPrecConst` term, it's just a hack to make the types nicer.)
* A `TextShow Color` instance implementing `showtPrec`, but instead of

  ```haskell
    instance text-show-3.2.2:TextShow.Classes.TextShow Color where
      text-show-3.2.2:TextShow.Classes.showtPrec = \ p_a7vf value_a7vg -> ...
  ```

  try this:

  ```haskell
    instance text-show-3.2.2:TextShow.Classes.TextShow Color where
      text-show-3.2.2:TextShow.Classes.showtPrec p_a7vf value_a7vg = ...
  ```

  I have a hunch eta-reduction might play a small but important role.

**Comment by andrewthad** [comment]
I've push more changes to my benchmark branch. Here are the results:

    benchmarking Enumeration Type (strict Text)/String Show, then Text.pack
    time                 107.5 ns   (107.3 ns .. 107.7 ns)
                         1.000 R²   (1.000 R² .. 1.000 R²)
    mean                 107.6 ns   (107.4 ns .. 107.8 ns)
    std dev              672.3 ps   (439.1 ps .. 1.040 ns)
                 
    benchmarking Enumeration Type (strict Text)/Text Show (TH)
    time                 86.46 ns   (86.28 ns .. 86.67 ns)
                         1.000 R²   (1.000 R² .. 1.000 R²)
    mean                 86.39 ns   (86.28 ns .. 86.61 ns)
    std dev              485.6 ps   (283.8 ps .. 850.5 ps)
                 
    benchmarking Enumeration Type (strict Text)/Text Show (showtPrec lambda)
    time                 7.382 ns   (7.367 ns .. 7.400 ns)
                         1.000 R²   (1.000 R² .. 1.000 R²)
    mean                 7.376 ns   (7.368 ns .. 7.394 ns)
    std dev              38.26 ps   (22.12 ps .. 58.62 ps)
                 
    benchmarking Enumeration Type (strict Text)/Text Show (showtPrec non-lambda)
    time                 7.653 ns   (7.645 ns .. 7.667 ns)
                         1.000 R²   (1.000 R² .. 1.000 R²)
    mean                 7.659 ns   (7.649 ns .. 7.689 ns)
    std dev              51.27 ps   (19.05 ps .. 106.6 ps)
                 
    benchmarking Enumeration Type (strict Text)/Manually written text show
    time                 8.532 ns   (8.521 ns .. 8.545 ns)
                         1.000 R²   (1.000 R² .. 1.000 R²)
    mean                 8.533 ns   (8.523 ns .. 8.551 ns)
    std dev              43.71 ps   (26.52 ps .. 76.54 ps)

Also, it's worth noting that the default implementation of `showt` doesn't use `showtPrec`. I had to change it in the instances I wrote.

**Comment by RyanGlScott** [comment]
Wow! So if I understand the results correctly:

1. Using a lambda or not doesn't make much of a difference.
2. Giving a non-default implementation of `showtPrec` can be much faster than going through `Builder`.

Thanks for benchmarking all of this, this is quite illuminating. One thing I should definitely do, now that you've pointed it out, is make the default implementations of `showt` and `showtl` be `showtPrec 0` and `showtlPrec 0`, respectively.

Another thing I should consider is how to address this performance issue. The most direct fix would be generating a definition for `showt` (and `showtl`, perhaps? Not sure how much worse it fares when going through a `Builder`) via `deriveTextShow`. The downside is that it would result in 2x (or 3x) the generated code.

We could:

1. Make `deriveTextShow` always generate a `showt` definition
2. Make this configurable via an `Options` argument to `deriveTextShowOptions`

Thoughts?

**Comment by RyanGlScott** [comment]
Indeed, I do suspect that manually implementing a `showtPrec` definition for sufficiently large product types could result in a performance hit. This reveals yet another inadequacy of `text-show`'s benchmark suite, since it doesn't benchmark such a handwritten `showtPrec` function!

I like the idea of having Template Haskell check if a datatype is an enumeration type (i.e., a datatype with at least one constructor, none of which have any fields) and using that as a metric for whether or not to generate a `showtPrec` definition. Here is what I'd envision an `Options` datatype to look like:

```haskell
newtype Options = Options { genTextMethods :: GenTextMethods }

data GenTextMethods
  = AlwaysTextMethods -- ^ Always generate
  | SometimesTextMethods -- ^ Only generate when text-show feels it's appropriate
  | NoTextMethods  -- ^ Never generate under any circumstances

defaultOptions :: Options
defaultOptions = Options { genTextMethods = SometimesTextMethods }
```

Before marching forth with implementing this, however, there are still some questions that someone (which could be you, or it could be me when I find enough free time) needs to answer:

1. What is the best criterion for determining when to generate a `showtPrec` definition? That is, at what point does `SometimesTextMethods` decide generating a `showtPrec` definition is a bad idea? Is it when the datatype isn't an enumeration type? If so, how much of a performance hit does generating a `showtPrec` definition for such a datatype incur over the default `showbPrec`-based definition?
2. Does the same metric (i.e., enumeration types) apply to `showtlPrec`? If so, how much of a performance hit does the `showbPrec`-based definition of `showtlPrec` incur over a manual definition? Is there a cutoff point like the one mentioned earlier at which we shouldn't generate a `showtlPrec` definition (i.e., product types)? If so, how much of a performance hit is involved?

**Comment by RyanGlScott** [comment]
I've pushed two commits which improve the state of affairs for showing nullary constructors using TH or generics. This isn't scientifically rigorous, but I can at least use the results from two Travis runs (before and after the changes) to illustrate the difference:

[Before the changes:](https://travis-ci.org/RyanGlScott/text-show/jobs/150079941#L1388)

```
benchmarking Enumeration type/String Show
time                 94.84 ns   (87.86 ns .. 103.6 ns)
                     0.976 R²   (0.965 R² .. 1.000 R²)
mean                 89.62 ns   (87.88 ns .. 94.66 ns)
std dev              7.856 ns   (163.5 ps .. 14.83 ns)
variance introduced by outliers: 88% (severely inflated)

benchmarking Enumeration type/String Show, then Text.pack
time                 254.0 ns   (253.6 ns .. 254.3 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 253.7 ns   (253.3 ns .. 254.1 ns)
std dev              1.215 ns   (874.8 ps .. 1.592 ns)

benchmarking Enumeration type/TextShow (TH)
time                 208.3 ns   (208.0 ns .. 208.6 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 208.5 ns   (208.2 ns .. 208.8 ns)
std dev              999.1 ps   (802.8 ps .. 1.459 ns)

benchmarking Enumeration type/TextShow (generics)
time                 601.1 ns   (600.6 ns .. 601.9 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 603.3 ns   (602.3 ns .. 604.2 ns)
std dev              3.359 ns   (2.888 ns .. 4.024 ns)

benchmarking Enumeration type/Manually written showt
time                 10.62 ns   (10.48 ns .. 10.89 ns)
                     0.985 R²   (0.974 R² .. 0.993 R²)
mean                 12.16 ns   (11.47 ns .. 12.97 ns)
std dev              2.585 ns   (2.126 ns .. 2.872 ns)
variance introduced by outliers: 98% (severely inflated)
```

[After the changes:](https://travis-ci.org/RyanGlScott/text-show/jobs/152089949#L1389)

```
benchmarking Enumeration type/String Show
time                 86.53 ns   (84.56 ns .. 88.37 ns)
                     0.997 R²   (0.994 R² .. 0.999 R²)
mean                 86.97 ns   (85.26 ns .. 91.77 ns)
std dev              8.656 ns   (3.921 ns .. 17.64 ns)
variance introduced by outliers: 91% (severely inflated)

benchmarking Enumeration type/String Show, then Text.pack
time                 158.4 ns   (150.5 ns .. 165.5 ns)
                     0.983 R²   (0.974 R² .. 0.993 R²)
mean                 146.7 ns   (142.3 ns .. 153.7 ns)
std dev              17.89 ns   (13.05 ns .. 25.38 ns)
variance introduced by outliers: 94% (severely inflated)

benchmarking Enumeration type/TextShow (TH)
time                 12.12 ns   (11.28 ns .. 12.97 ns)
                     0.976 R²   (0.970 R² .. 0.990 R²)
mean                 12.14 ns   (11.61 ns .. 12.72 ns)
std dev              1.849 ns   (1.624 ns .. 2.113 ns)
variance introduced by outliers: 96% (severely inflated)

benchmarking Enumeration type/TextShow (generics)
time                 456.2 ns   (430.6 ns .. 474.4 ns)
                     0.977 R²   (0.966 R² .. 0.986 R²)
mean                 446.5 ns   (423.5 ns .. 473.0 ns)
std dev              85.36 ns   (75.48 ns .. 97.56 ns)
variance introduced by outliers: 97% (severely inflated)

benchmarking Enumeration type/Manually written showt
time                 15.23 ns   (14.68 ns .. 15.54 ns)
                     0.988 R²   (0.978 R² .. 0.993 R²)
mean                 13.78 ns   (12.77 ns .. 14.54 ns)
std dev              2.564 ns   (2.049 ns .. 2.939 ns)
variance introduced by outliers: 98% (severely inflated)
```

Note in particular the difference in `Enumeration type/TextShow (TH)` (208.3 ns vs. 12.12 ns)!

**Comment by RyanGlScott** [comment]
I think this can be closed.

**Comment by RyanGlScott** [comment]
Uploaded [`text-show-3.4`](http://hackage.haskell.org/package/text-show-3.4) to Hackage, which contains these changes.
