### ISSUE TITLE
text-show-0.7 test suite failure

### ISSUE THREAD

**Issue by peti** [RyanGlScott/text-show#5]
Citing from http://hydra.cryp.to/build/655840/nixlog/1/raw:

    print behavior:                                                   FAIL (0.02s)
      *** Failed! Falsifiable (after 66 tests and 1 shrink): 
      ""
      Use --quickcheck-replay '65 TFGenR 7A11967F6D8602ED44048E8E10577281C39D7B82355D45680D4F1C1496ED0955 0 16383 14 0' to reproduce.

**Comment by RyanGlScott** [comment]
Hm... this is a strange failure. I can't reproduce this on my machine with the same seed, nor does Travis-CI catch this. This test simply prints random strings to stdout (using Prelude's `print` and text-show's `print`), catches the output with the `silently` library, and checks them to see if they're the same. It'd be useful to see what the stdout output for that test case was, because otherwise I can't tell what's going wrong.

**Comment by peti** [comment]
Well, I'm afraid that I've provided all the information that's available to me.

**Comment by RyanGlScott** [comment]
In any case, I think the bug is probably related to `putStrLn` from `text` or `capture` from `silently`, so I'll just comment out those tests. I've reuploaded to Hackage as `text-show-0.7.0.1`—let me know if there are other issues.
